### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by pi8027**

### CODE REVIEW

**Comment by pi8027** [comment]
I have a hard time understanding the following failure. Why `coq-elpi` is required to be `dev` here?
```
  The following dependencies couldn't be met:
    - coq-mathcomp-algebra-tactics -> coq-elpi >= dev -> ocaml >= 4.07.0
        base of this switch (use `--unlock-base' to force)
    - coq-mathcomp-algebra-tactics -> coq-elpi >= dev -> coq (< 8.14~ | >= dev)
        not available because the package is pinned to version 8.14+rc1
```

**Comment by pi8027** [comment]
Let's remove `mathcomp/mathcomp:1.12.0-coq-8.14` for now and try it later.

**Comment by gares** [comment]
does the image use the extra-dev opam repo? Because coq-elpi 1.11.2, compatible with Coq 8.14+rc1, is only there (not in released, since it depends on Coq 8.14+rc1 which is in extra-dev...

**Comment by pi8027** [comment]
The image seems to use the `coq-extra-dev` repo. I need it for mczify for the same reason. https://github.com/math-comp/algebra-tactics/runs/3707690608?check_suite_focus=true

**Comment by pi8027** [comment]
The Docker image seems to use the OPAM switch 4.05.0, but coq-elpi >= 1.11 requires OCaml >= 4.07.0.

**Pull request merged**
