### PR TITLE
[WIP] Add an option: Set/Unset Algebra Tactics Debug

### PR DESCRIPTION
**Pull request by pi8027**

### CODE REVIEW

**Comment by pi8027** [comment]
@gares Apparently, `Require Import lib` does not make an option added by `lib` using `coq.option.add` available. I will open an issue.

**Comment by gares** [comment]
I see. Anyway, for debug it is better to use another API which I shall bound

**Comment by gares** [comment]
Are you sure a #[debug] or #[verbose] attribute would not be better?

**Comment by pi8027** [comment]
Ah, using the attribute mechanism is indeed better.

**Comment by pi8027** [comment]
@gares It seems that tactic notations cannot take attributes. Do I miss something? https://github.com/math-comp/algebra-tactics/blob/d2882619a5ee9f98fd0b92c3efb8d82eac396bb0/theories/ring.v#L705-L706

**Comment by gares** [comment]
some limitations: https://github.com/LPCIC/coq-elpi#attributes

**Comment by gares** [comment]
Now that I think about it, if you pick a different syntax for the delimiter, then there is no conflict... but yea, not super nice :-/

**Pull request closed without merging**
