### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by pi8027**

### CODE REVIEW

**Comment by pi8027** [comment]
@gares Hi, can the following error be turned into a warning, so that we can keep compatibility with older versions of Coq?
```
  # File "./theories/lra.v", line 397, characters 0-15:
  # Error: The command 'Elpi Typecheck' is deprecated (and does nothing) since
  # type checking is now performed by 'Elpi Accumulate'.
  # [elpi.typecheck-syntax,elpi.deprecated,deprecated,elpi,default]
```

**Comment by gares** [comment]
Add a -typecheck-syntax, I think I did that in HB

**Comment by pi8027** [comment]
I still don't get why it is not a warning but an error by default, but thanks anyway.

**Comment by gares** [comment]
I changed the default in 2.3.0

**Pull request merged**
